#!/usr/bin/env sh
# https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc

yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa

# Global settings
yabai -m config \
  external_bar               all:25:0     \
  mouse_follows_focus        off          \
  focus_follows_mouse        off          \
  window_origin_display      default      \
  window_placement           second_child \
  window_topmost             off          \
  window_shadow              on           \
  window_opacity             on           \
  window_opacity_duration    0.0          \
  window_animation_duration  0.0          \
  active_window_opacity      1.0          \
  normal_window_opacity      1.0          \
  window_border              on           \
  window_border_hidpi        off          \
  window_border_blur         off          \
  window_border_width        1            \
  window_border_radius       0            \
  active_window_border_color 0xFF003E00F  \
  split_ratio                0.50         \
  split_type                 auto         \
  auto_balance               off

# Space settings
yabai -m config \
  layout         bsp \
  top_padding    0   \
  bottom_padding 0   \
  left_padding   0   \
  right_padding  0   \
  window_gap     0

# Rule
alias yr='yabai -m rule --add'
yr app="^Activity Monitor$" manage=off
yr app="^Calculator$" manage=off
yr app="^Cisco AnyConnect Secure Mobility Client$" sticky=on manage=off
yr app="^Disk Utility$" manage=off
yr app="^Finder$" manage=off
yr app="^Karabiner-Elements$" manage=off
yr app="^Karabiner-EventViewer$" manage=off
yr app="^KeePassXC$" manage=off
yr app="^Path Finder$" manage=off
yr app="^QuickTime Player$" manage=off
yr app="^Slack$" space=2
yr app="^Spotify$" space=4
yr app="^System Information$" manage=off
yr app="^System Preferences$" manage=off
# yr app="^(Brave|Google\ Chrome)$" layer=below
# yr app="^kitty$" layer=above

# yabai -m signal --add event=window_destroyed action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"
# yabai -m signal --add event=application_terminated action="yabai -m query --windows --window &> /dev/null || yabai -m window --focus mouse"

echo "yabai configuration loaded.."
# open -na Spotify
