#!/usr/bin/env sh
# https://github.com/koekeishiya/yabai/blob/master/doc/yabai.asciidoc

# Global settings
yabai -m config \
  external_bar               all:25:0     \
  mouse_follows_focus        off          \
  focus_follows_mouse        off          \
  window_origin_display      default      \
  window_placement           second_child \
  window_topmost             on           \
  window_shadow              on           \
  window_opacity             on           \
  window_opacity_duration    0.0          \
  window_animation_duration  0.0          \
  active_window_opacity      1.0          \
  normal_window_opacity      0.83         \
  window_border              on           \
  window_border_hidpi        off          \
  window_border_blur         off          \
  window_border_width        2            \
  window_border_radius       0            \
  active_window_border_color 0xFF003E00F  \
  split_ratio                0.50         \
  split_type                 auto         \
  auto_balance               on

# Space settings
yabai -m config \
  layout         bsp \
  top_padding    0   \
  bottom_padding 0   \
  left_padding   0   \
  right_padding  0   \
  window_gap     0

# Rule
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Cisco AnyConnect Secure Mobility Client$" sticky=on manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^Finder$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^KeePassXC$" manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Slack$" space=2
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^System Preferences$" manage=off

echo "yabai configuration loaded.."
